# Generated by Django 3.2.9 on 2021-11-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('year_type', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cars',
            },
        ),
        migrations.CreateModel(
            name='FrontTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('width', models.PositiveIntegerField()),
                ('aspect_ratio', models.PositiveIntegerField()),
                ('wheel_size', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'front_tires',
            },
        ),
        migrations.CreateModel(
            name='RearTire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('width', models.PositiveIntegerField()),
                ('aspect_ratio', models.PositiveIntegerField()),
                ('wheel_size', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'rear_tires',
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spec', to='cars.car')),
                ('front_tire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.fronttire')),
                ('rear_tire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.reartire')),
            ],
            options={
                'db_table': 'specs',
            },
        ),
    ]
