# Generated by Django 3.2.5 on 2021-11-25 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
        migrations.AlterModelTable(
            name='fronttire',
            table='front_tires',
        ),
        migrations.AlterModelTable(
            name='reartire',
            table='rear_tires',
        ),
        migrations.AlterModelTable(
            name='spec',
            table='specs',
        ),
    ]
